### ISSUE TITLE
Disable TextFormatter key sorting

### ISSUE THREAD

**Issue by initzero** [Sirupsen/logrus#102]
It would be useful to be able to disable the TextFormatter from sorting fields.

**Comment by c4milo** [comment]
+1 here, it should not be forced.

**Comment by Sirupsen** [comment]
Aye, could be an option like `ForceColors`.

**Comment by c4milo** [comment]
yeah, something like `SortFields`

**Comment by Sirupsen** [comment]
I'll happily accept a patch

**Comment by steevel** [comment]
I looked in to this and in order to do this we probably need to add another WithFields*-method since logrus.Fields{} is of type map[string]interface{}, which by nature is "random".

I have been playing around with making WithField() either take a ...interface{} and thus be able to handle multiple key/value pairs (which we could keep sorted) or to just add a WithFieldList() not to make people confused with the name being singular.

Any input on what would feel most natural?

**Comment by Sirupsen** [comment]
Fixed in https://github.com/Sirupsen/logrus/commit/538395b333d25a59cce4e30b2a41da7354d10865

**Comment by steevel** [comment]
The solution isn't this easy since entry.Data is of type Fields (map) and maps are random by nature.

Code:
logrus.SetFormatter(&logrus.TextFormatter{DisableSorting: true})
logrus.WithFields(logrus.Fields{"one": 1, "two": 2, "three": 3, "four": 4}).Info("one")
logrus.WithFields(logrus.Fields{"two": 2, "one": 1, "four": 4, "three": 3}).Info("two")
logrus.WithFields(logrus.Fields{"three": 3, "four": 4, "two": 2, "one": 1}).Info("three")

Output of run 1:
INFO[0000] one                                           one=1 two=2 three=3 four=4
INFO[0000] two                                           one=1 four=4 three=3 two=2
INFO[0000] three                                         one=1 three=3 four=4 two=2

Output of run 2:
INFO[0000] one                                           one=1 two=2 three=3 four=4
INFO[0000] two                                           two=2 one=1 four=4 three=3
INFO[0000] three                                         one=1 three=3 four=4 two=2

Notice how they now are random instead of sorted. We would have to change from the map type to a slice in order to implement this for real. Where they align correctly to their input is just pure luck.

**Comment by Sirupsen** [comment]
Yes, that's what I expected, most aggregators are fine with that—I didn't do a full reimplementation with a slice. I'd happily accept a patch that does.
