### ISSUE TITLE
What can I do with WithContext()?

### ISSUE THREAD

**Issue by dionysius** [sirupsen/logrus#1045]
Example:
```golang
package main

import (
	"context"
	"time"

	"github.com/sirupsen/logrus"
)

type transaction string

func main() {
	log := logrus.StandardLogger()

	ctx := context.Background()
	ctx = context.WithValue(ctx, "transactionid", transaction("bar"))
	ctx, _ = context.WithTimeout(ctx, 5*time.Minute)

	err := fmt.Errorf("boo")

	log.WithContext(ctx).WithError(err).Print("hello")
}
```
Output:
```
INFO[0000] hello                                         error=boo
```

I know I can get the context back on *Entry.Context, but I kinda expected that context fields somehow go into the logrus fields output too - like WithError() does for errors.

Independent from what I want to do, what can I do with WithContext(), what's its use case?

**Comment by pradykaushik** [comment]
Reading through [code](https://github.com/sirupsen/logrus/blob/master/entry.go#L73) I see that you can use context to pass information to hooks for example.

**Comment by freeformz** [comment]
What @pradykaushik said.

There is no way for logrus to inspect a context.Context (it's an interface) to determine it's contents w/o also not knowing all the keys used to store values in it. `WithContext` allows for code using a FieldLogger to inject a Context (with one or more know keys) that a hook would be able to interpret (because it knows the keys used to store data) or for some sort of cancelation.

**Comment by freeformz** [comment]
PS: What you may be looking for is `WithField` and `WIthFields` for collecting logging "context".

**Comment by dionysius** [comment]
Thank you, I was just wondering what the intention of context there was, which is answered.
