### ISSUE TITLE
Print FatalLevel log, exit function will not be called?

### ISSUE THREAD

**Issue by edoger** [sirupsen/logrus#1078]
l := logrus.New()
l.ExitFunc = func(int) { fmt.Println("exit") }

l.Log(logrus.FatalLevel, "test") //  The exit function was not called!
l.Fatal("test") // The exit function is called!

Designed so?

**Comment by kaedys** [comment]
(Logger).Log(logrus.FatalLevel, ...) also will not actually _exit the program_.  `(Logger).Fatal` literally just called `(Logger).Log(FatalLevel)` followed by `(Logger).Exit(1)`.  So it makes sense that an isolated call to `Log()`, even with the `FatalLevel` specified, would not call the exit func, because it is also not terminating the program, unlike `Fatal()`.
