### ISSUE TITLE
Improving logrus performance

### ISSUE THREAD

**Issue by pjvds** [sirupsen/logrus#125]
I recently migrated some parts of our code from `glog` to `logrus` and noticed some serious decrease (close to 45%) in performance. We are not doing anything fancy, just level logging to a file. So I started to profile and noticed that a lot of time is spend on `memmove` and `scanblock`. When I accumulate all garbage collection related operations I see that roughly 26% of the time is spend on garbage collection.

One of the hotspots I discovered it the formatting and I spiked a few tweaks to introduce pooled buffers. This will change the API since buffers need to be released after they have been used.

My changes have a huge impact on the code and break almost all hooks. Not in a bad way, it's just because types are slightly different. So, before I spend a lot of time trying to complete this, I want to discuss if the logrus community would like to move into this direction?

The first benchmark's show an performance improvement 12% for small log entries and up to 35% for larger entries with an mean of 28%. My assumption is that is also significantly lowers memory usage and because it generates less garbage, we spend less time in Go's stop the world garbage collector.

My concrete question: is the logrus community willing to accept changes that effect the entire codebase and `hook` interface to gain performance and generate less garbage? If so, I want to discuss the next steps and willing to invest time in it to make it happen.

**Comment by Sirupsen** [comment]
Hi @pjvds thanks a lot for your input! 

This is the actually the first time I've heard of people who've been running into serious performance issues with the logger in production. Performance hasn't been a hardcore goal (e.g. in some cases we've favoured nice API and usability over performance, although obviously harvesting any performance benefits we could) because the time spent in logrus in the applications I have has been negligible, likely because I log much less than you do. However, if you're seeing problems, let's discuss how we can best solve them.

How much are you logging? 

Can you track down more specifically which codepath is slow (you're mentioning the low-level calls which is great)? It might be a hook or a specific part of the formatter.

I have a hunch it has to do with the formatter, e.g. it's doing a sort by default which is notoriously slow (but hasn't been a big deal in my cases).

**Comment by pi3r** [comment]
@pjvds do you have a branch with your current changes? I'm just curious :)

**Comment by StabbyCutyou** [comment]
I would be interested in seeing the proposed differences to the surface API this might entail. I love how easy to use and extend logrus messages are, but with an app that has very tight performance constraints, I would additionally love to know that I'm not losing time in my logging framework of choice.

**Comment by placeybordeaux** [comment]
As a consumer I am willing to refactor code to gain a performance increase assuming the numbers you are quoting are realistic. However logrus is imported by [702 packages](https://godoc.org/github.com/Sirupsen/logrus?importers). Breaking changes are pretty rough, any way to offer a new version or different API for the faster stuff?

**Comment by cep21** [comment]
I as well have seem performance issues w/ logrus related to the garbage creation.  I solved this by removing the WithField() calls for debug logs by using the following function.

```golang
// Debug to logger a key/value pair and message.  Intended to save the mem alloc that WithField creates
func Debug(l *logrus.Logger, key string, val interface{}, msg string) {
	if l.Level >= logrus.DebugLevel {
		l.WithField(key, val).Debug(msg)
	}
}
```

**Comment by Sirupsen** [comment]
@cep21 would being able to pass a function that's lazily evaluated to `WithField{,s}` work for you?

**Comment by cep21** [comment]
For me, on this issue, it was the large number of allocs and the GC pressure I was trying to reduce.  l.WithField(key, val).Debug(msg) requires a few allocs even when I'm not at debug level.

The only I can see to get around this is to reverse the order.

```
  l.Debug(msg).WithField(key, val).Fire()
```

With this order of operations, l.Debug(msg) could return a no-op singleton and make any future calls no-op non memory allocs.  With the order logrus currently has, l.WithField(key, val) requires an alloc because it doesn't know that Debug is coming next.

**Comment by imkira** [comment]
Good to find more people discussing this!

@cep21 Actually I am submitting a PR to fix the first issue you talked about.
Regarding the logger.WithField problem, I am also proposing a similar approach to yours.
Please check #154

I am basically proposing either

- inverted logic: log.Info(...).WithFields(...)
- like your Fire but trying to be semver compatible: ```log.WithLevel(Info).WithFields(...).Log(...) ```

**Comment by pmoust** [comment]
Rel: PERF: use buffer pool in json formatter #755

**Comment by alexstov** [comment]
Hi, my observation with WithFields is that it over-allocates memory even when it doesn't have too. In this particular example (see attached) the log level is set to 'warn', but a call of Trace allocated ~32Mb. Has anybody found a reliable workaround for this issue? Thanks!
![image](https://user-images.githubusercontent.com/52447010/70085760-28317e80-15ce-11ea-872b-e993ee4609ba.png)
