### ISSUE TITLE
Prevent/stop an entry being write in the hook

### ISSUE THREAD

**Issue by itplayer** [sirupsen/logrus#1346]
Sorry if this is not the place to ask such question.

Not sure if there is a way to stop/prevent an entry being write to the log (or stdout) if the entry contains specific field.
```
func (hook *Hook) Fire(entry *log.Entry) error {
	line, err := entry.Bytes()
	someId:= entry.Data[someId].(string)

	if err != nil {
		return err
	}

	if contains("xyz", tenantId) {
		//I think to we need something here to clear the entry or stop the entry being write after then
	} 
```

**Comment by edoger** [comment]
@itplayer Hooks do not prevent log output, that may require custom formatters to handle field exclusions, and you need custom writers to prevent specific log output.

**Comment by itplayer** [comment]
@edoger Thanks for the reply.
Could you share more clues for the custom writer?

If I  set the writer for the hook to the **os.Stdout** then I tried to write nil in the hook while it detects a certain field, there was no such log being output. But I doubt that is still invoking a write(I/O), right? 

What I really need is that we can ignore logs without any I/O, any idea?

**Comment by edoger** [comment]
@itplayer For the current status of this project, you need to wrap **io.Stdout** as another writer. When you detect nil, you can directly return, for example:
```go
type YourWriter struct {
	w io.Writer // os.Stdout
}

func (w *YourWriter) Write(p []byte) (int, error) {
	if len(p) == 0 {
		return 0, nil
	}
	return w.w.Write(p)
}
```
If performance is a problem, you can try our other log library: [zkits-logger](https://github.com/edoger/zkits-logger) 
The usage style is similar to that of logrus, but there are also many differences.

**Comment by itplayer** [comment]
@edoger Thank you so much for the guidance.
So you mean that inject a custom writer as you mentioned above to the logger, then write nil in the hook when a certain field is detected as the following but the writer here is the custom one like above?

`			
if contains(keys, k) {				
				_, err = hook.Writer.Write(line)
				return err
			} else {				
				_, err = hook.Writer.Write(nil)
				return err
			}

`

**Comment by edoger** [comment]
@itplayer You know the behavior of logrus from the source code, they are here:
[entry.go#L242](https://github.com/sirupsen/logrus/blob/f8bf7650dccb756cea26edaf9217aab85500fe07/entry.go#L242)

1. Trigger the hook.
2. Reset the write buffer.
3. Format log data.
4. Output log.

**As you can see, the hook cannot prevent the log from being written to the output writer.**
If you set the writer to **io.Discard**, you can prevent log output, but you must suffer the performance penalty caused by a log format.

```go
Logger.SetOutput(io.Discard)

// Your Hook.Fire
line, err := entry.Bytes()
if contains(keys, k) {				
	_, err = hook.Writer.Write(line)
	return err
}
```

Twice repeated log formatting:
https://github.com/sirupsen/logrus/blob/f8bf7650dccb756cea26edaf9217aab85500fe07/entry.go#L90
https://github.com/sirupsen/logrus/blob/f8bf7650dccb756cea26edaf9217aab85500fe07/entry.go#L289

**Comment by itplayer** [comment]
@edoger Thanks for the details.
So back to the original problem, it seems the only way to prevent unwanted logs being written to file is a custom writer that wraps os.Stdout, right?

**Comment by edoger** [comment]
@itplayer Yes, This is the only way currently.
