### ISSUE TITLE
deadlock when use in multi goroutine

### ISSUE THREAD

**Issue by dtdyq** [sirupsen/logrus#1375]
code :
writer, err := rotatelogs.New(

		path.Join(opt.LogDir, opt.LogFile+".%Y-%m-%d"),
		rotatelogs.WithMaxAge(30*24*time.Hour), 
		rotatelogs.WithRotationTime(24*time.Hour), 
		//rotatelogs.WithRotationCount(3),
		//rotatelogs.WithRotationTime(time.Minute),
	)
	if err != nil {
		panic(err)
	}
	lfHook := lfshook.NewHook(writer, ll.Formatter)
	ll.AddHook(lfHook)

goroutine state:
goroutine 1 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0xc00006cc00?, 0x30?, 0x0?)
	/root/gows/go/src/runtime/sema.go:77 +0x26
sync.(*Mutex).lockSlow(0xc000135330)
	/root/gows/go/src/sync/mutex.go:171 +0x165
sync.(*Mutex).Lock(...)
	/root/gows/go/src/sync/mutex.go:90
github.com/sirupsen/logrus.(*MutexWrap).Lock(...)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/logger.go:61
github.com/sirupsen/logrus.(*Entry).log(0xc0001dbf10, 0x4, {0xc000215fd0, 0xe})
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:233 +0x305
github.com/sirupsen/logrus.(*Entry).Log(0xc0001dbf10, 0x4, {0xc00013dea0?, 0x10?, 0x909560?})
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Logger).Log(0xc000135300, 0x4, {0xc00013dea0, 0x1, 0x1})
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/logger.go:204 +0x65
github.com/sirupsen/logrus.(*Logger).Info(...)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.0/logger.go:226
netgo/common/logs.(*LogrusLogger).Info(0x3b9aca00?, {0x9baf6b?, 0xe?}, {0x0?, 0x0?, 0x0?})
	/root/root/gows/netgo/common/logs/logrus.go:63 +0x72

why cause that ?

**Comment by ozfive** [comment]
The deadlock seems to be caused by the MutexWrap defined in the Logger struct of logrus. The MutexWrap is used to synchronize writes to the log, but it can be disabled by calling SetNoLock() on the logger. The default behavior is to use locking, which causes a deadlock when multiple goroutines attempt to write to the same log file simultaneously.

To resolve the deadlock, disable the lock on the logger instance using SetNoLock(). Disabling the lock will make the logger instance unsafe for concurrent writes, so it should only be done if you can guarantee that only one goroutine will be writing to the log file at any given time.

Example of SetNoLock()

```go
package main

import (
	"github.com/sirupsen/logrus"
)

func main() {
	logger := logrus.New()

	// disable locking
	logger.SetNoLock()

	// log some messages
	logger.Info("This is an info message")
	logger.Warn("This is a warning message")
}
```

A way to resolve this issue with multiple goroutines attempting to write to the log would be to use a separate logger instance for each goroutine.

```go
package main

import (
    "github.com/sirupsen/logrus"
)

func main() {
    // Create a new logger instance for each goroutine
    logger1 := logrus.New()
    logger2 := logrus.New()

    // Start goroutines and pass the logger instances as arguments
    go doSomething(logger1)
    go doSomethingElse(logger2)

    // Wait for the goroutines to finish
    // ...
}

func doSomething(logger *logrus.Logger) {
    logger.Info("Doing something...")
    // ...
}

func doSomethingElse(logger *logrus.Logger) {
    logger.Info("Doing something else...")
    // ...
}
```

A better solution for multiple goroutines would be to create a new logger instance with a unique name for each goroutine, and then pass that logger instance to each goroutine or use a context to propagate the logger instance. The logger instance can be created with a custom formatter and output destination if needed.

```go
package main

import (
	"context"

	"github.com/sirupsen/logrus"
)

func worker(ctx context.Context, entry *logrus.Entry) {
	for {
		select {
		case <-ctx.Done():
			return
		default:
			entry.Info("worker is running")
		}
	}
}

func main() {
	parentLogger := logrus.New()

	ctx := context.Background()

	for i := 0; i < 5; i++ {
		logger := parentLogger.WithField("worker_id", i)
		go worker(context.WithValue(ctx, "logger", logger), logger)
	}
}
```

**Comment by ozfive** [comment]
You can also use a logging package that is designed to be used in a concurrent environment, such as Zap or Log15. These logging packages have been specifically designed to be thread-safe and can handle multiple goroutines logging concurrently without causing any issues like deadlocks.
