### ISSUE TITLE
What is the purpose of [0000]?

### ISSUE THREAD

**Issue by iamthemuffinman** [Sirupsen/logrus#163]
I'm curious as to why each log level, INFO, FATA, etc has a [0000] attached to it? What is the purpose of it? It's ugly and doesn't seem to give you any useful information. Another random, somewhat unrelated question. Why is fatal shortened to FATA? Why not just add the L? Thanks in advance!

**Comment by JoeBruner** [comment]
The [0000] is the timestamp since the program started.  It's not always just 0000, just for short running programs.  See https://github.com/Sirupsen/logrus/blob/master/text_formatter.go#L51

FATA is shortened to 4 letters to be consistent with the other logging levels.  That way, when you look at your logs, everything is the same level of indentation.

**Comment by iamthemuffinman** [comment]
Ah. Thanks!

**Comment by mmacheerpuppy** [comment]
@2bitProgammer  Hi! Thanks for this, is there a way for me to use a fully qualified `FATAL` with the default config?

**Comment by serdarkkts** [comment]
@mmacheerpuppy You can just set `DisableLevelTruncation` field to `true`
