### ISSUE TITLE
About the log formatter

### ISSUE THREAD

**Issue by hyper-carrot** [Sirupsen/logrus#240]
I initialized my logger base on logrus like this:
```go
func NewLogger(projectName string) *logger_logrus {
	innerLogger := logrus.New()
	innerLogger.Formatter = &logrus.TextFormatter{FullTimestamp: true}
	innerLogger.Level = logrus.DebugLevel
	return &logger_logrus{projectName: projectName, inner: innerLogger}
}
```
I used it then ran my server:
```bash
# myserver 2>&1
INFO[2015-09-01T18:00:39+08:00] [main.main | myserver.go:60]: Start front server with address ':8080'...
```
It works the way I want.

But, it seems to be what went wrong when I ran it like this:
```bash
# myserver 2>&1 | tee a.log
time="2015-09-01T18:00:42+08:00" level=info msg="[main.main | myserver.go:60]: Start front server with address ':8080'..."
```
The log formatter is wrong. Any suggestion? Thanks.

**Comment by ryanfaerman** [comment]
:+1: I'm seeing the same issue when I create my own formatter.

**Comment by aybabtme** [comment]
@hyper-carrot the `TextFormatter` detects if the output is an interactive console. If it is, the formatting is made to be colored and pleasantly looking. If it's not an interactive console, then the formatting follows the [`logfmt`][1] format.

When you redirect `stderr` to `stdout`, and then pipe `stdout` to a another process, `TextFormatter` detects that the output is not an interactive console and prints in logfmt. From the point of view of your app, the `stdout -> stdin` pipe that ends in process `tee` is not the interactive console that `tee` sees as its `stdout/stderr`, which is why although you get the output in your terminal, the logs are in `logfmt` shape.

Hope this explains =]

[1]:https://brandur.org/logfmt

**Comment by hyper-carrot** [comment]
@aybabtme Yes, thanks a lot!

How can I resolve it?

**Comment by aybabtme** [comment]
@hyper-carrot I'm not sure what your goal here is? You want `tee` to print colors? What's your end goal, if you zoom out?

**Comment by hyper-carrot** [comment]
@aybabtme I only want to look the log with text format (NOT JSON format).

**Comment by aybabtme** [comment]
If I were you, I'd embrace `logfmt` or `JSON` formatting, they're very convenient formats to log in. They're easy to parse and search. If you want to make them more visually appealing, you can use tools like my [`humanlog`][1]:

```
# go get github.com/aybabtme/humanlog/...
# myserver 2>&1 | tee a.log | humanlog
```

[1]: https://github.com/aybabtme/humanlog

**Comment by hyper-carrot** [comment]
@aybabtme Great! I see, thank you for your patience to answer. :+1:
