### ISSUE TITLE
Preserve fields order in logger output

### ISSUE THREAD

**Issue by jrosiek** [Sirupsen/logrus#329]
It would be great if the fields appear in the order the user specified. This way we could put more important/shorter fields at the beginning of log message.

**Comment by aybabtme** [comment]
Thanks @jrosiek.  You can achieve this by implementing your own formatter. See https://github.com/Sirupsen/logrus/blob/master/formatter.go#L7-L19 for how to do this.

**Comment by ear** [comment]
@aybabtme could you elaborate a bit? The [Entry type](https://github.com/Sirupsen/logrus/blob/master/entry.go#L21-L22) passed to the formatter you linked to has a `Data` field of type [Fields](https://github.com/Sirupsen/logrus/blob/master/logrus.go#L9-L10) that is a `map` which inherently does not preserve ordering of the pairs added to it with calls to `WithField` and `WithFields`. How are you suggesting to implement this in the formatter? Thank you in advance!

**Comment by aybabtme** [comment]
@ear in the formatter, before printing the fields, you'd put them in a type that can be sorted, sort that type and then print them in order

**Comment by ear** [comment]
@aybabtme I see. I do not think that is a solution to the original problem in that it does not _necessarily_ preserve either the order of calls to `WithField` / `WithFields` nor their arguments order. 😢

**Comment by aybabtme** [comment]
@ear I'm not sure I understand then. If you have something specific in mind, I think it will be easier if you prepare a PR and we can discuss the merits at that point? I'll be happy to look over it, just ping me.

**Comment by ear** [comment]
@aybabtme ok! One major use of this that I can think of stems from PR #320. I.e. when you construct a `FieldLogger` it'd be nice if every subsequent use of it would have the same structure: first the fields already set, then the eventual new ones added afterwards to code that has been given the object.

In addition to that I personally think it would be nicer to have the fields sorted by the order of `WithField(s)` calls and their argument position if not for anything else than to help readability of logs. This is not a major issue because if _can_ be solved by your approach, so that one's eyes don't have to jump around in a zig-zag pattern every time they want to see the evolution of a particular field's value in time.

On the other hand having a logger that respect `WithField(s)` order and their argument order in the display of the fields during logging would solve both of those concerns at once. I have not tried to put it together because I don't know what Go type would be best for the job. I do add a slice to a map to add the information about the order of the keys in other code sometimes. Would that be an alright approach?

Another issue I can think of is that WithFields uses a map as its argument's type. There is no "argument order" per se to keep track of. I guess making it a variadic function could work but would it be pretty enough to use in practice? I kinda hope so.

I hope this was not too much, thank you for both answering swiftly and responding. I hit "subscribe" on this issue a while ago because I was interested in knowing exactly how this would work in future logrus. Seeing it closed summarily made me somewhat sad. You asking for details and code is excellent 👍

**Comment by aybabtme** [comment]
@ear I think what you're looking for won't be possible in the current iteration of logrus. There's an issue (#234) that proposes using a persistent, immutable datastructure instead of a Go `map`, and @Sirupsen was considering using that. If this happens, we could try to use a sorted map, so that you we could have the behavior you desire. Or at least allow specifying the map implementation by using interfaces or something.

Unfortunately, in the current state of things, I think you'll have to resort to writing your own formatter that handles that stuff. It won't support `WithField(s)` order, but that'll at least get you somewhere closer.

* * * 

On a side note, I think your real problem (making your logs more readable) can be better solved not by tweaking the internals of logrus, but instead using a tool that prettyprints your logs. I wrote such a tool, and it supports JSON and logfmt logs. In my opinion, it's the best way to handle this issue.

See https://github.com/aybabtme/humanlog

* * *

I'll mark this with a label for a 1.0 rewrite, so we can revisit the question of allowing sorted maps in the future.
