### ISSUE TITLE
Can log file auto split by hour or day?

### ISSUE THREAD

**Issue by jinleileiking** [Sirupsen/logrus#387]

**Comment by aarongreenlee** [comment]
@jinleileiking, this is not a feature built into logrus. Log rotation may be the solution you are looking for.

Here are some links that may help:
* http://www.linuxcommand.org/man_pages/logrotate8.html
* http://www.cyberciti.biz/faq/how-do-i-rotate-log-files/
* https://support.rackspace.com/how-to/understanding-logrotate-utility/

**Comment by jinleileiking** [comment]
Thanks a lot.

**Comment by janflyborg** [comment]
For those of us developing cross-platform services that must also be able to run in Windows, this does not help. Wouldn't it be a good thing if there existed API:s so that it was possible to plug in the desired behavior for platforms where the log rotation must be performed by the program itself?

Windows is one obvious case and embedded devices where logrotate is unavailable is another.

All that is needed is a way to ensure that the log file is not written to while the log rotation is being performed. If logger.mu was public this would have been easy, but I would prefer an API.

Would such a pull request be considered for inclusion?

**Comment by stevvooe** [comment]
@janflyborg Surely, windows can rotate a file? IO redirection is supported.

**Comment by janflyborg** [comment]
What I meant was that Windows normally does not have logrotate available (https://linux.die.net/man/8/logrotate) and sometimes the same thing applies for embedded devices where a cut-down version of Linux is running. But I am not using logrus anymore.
