### ISSUE TITLE
"Logger as an io.Writer"

### ISSUE THREAD

**Issue by psmason** [sirupsen/logrus#436]
```
package main

import (
    "github.com/Sirupsen/logrus"
    "log"
)

func main() {
    logrusInputWriter := logrus.StandardLogger().Writer()
    log.SetOutput(logrusInputWriter)
    log.Println("will this print?")
    logrusInputWriter.Close()
}
```

The issue is that the logging event is not guaranteed to happen, from a race between process exit and the read end of the pipe waking up.  A solution I've  played with involves Writer() returning not

```
*io.PipeWriter
```

but rather

```
io.WriteCloser
```

with the underlying returned struct using synchronization tools in the implementation.  A sample gist is viewable at https://gist.github.com/psmason/839de8ddbdfa0ce21e30680987aa52cb.

Unfortunately it looks like fixing this in a backwards compatible way will be difficult, without playing with the return type.

**Comment by pasztorpisti** [comment]
In my opinion logrus shouldn't provide `Logger.Writer` - a generic builtin solution to this problem. Even if it provided one, it should be a completely separate package with building blocks similar to the example below.

Implementing an `io.Writer` that bridges the gap between the standard `log` pkg and `logrus` is straightforward and requires no go routines, pipes or other kind of black magic:

```go
package main

import (
	"github.com/sirupsen/logrus"
	"log"
)

func main() {
	log.SetFlags(0)
	log.SetOutput(log2LogrusWriter{
		logger: logrus.StandardLogger(),
	})

	log.Print("meow")
	logrus.Info("woof")
}

// log2LogrusWriter exploits the documented fact that the standard
// log pkg sends each log entry as a single io.Writer.Write call:
// https://golang.org/pkg/log/#Logger
type log2LogrusWriter struct {
	logger *logrus.Logger
}

func (log2LogrusWriter) Write(b []byte) (int, error) {
	n := len(b)
	if n > 0 && b[n-1] == '\n' {
		b = b[:n-1]
	}
	logrus.WithField("logger", "std").Warning(string(b))
	return n, nil
}
```

The above solution has several advantages over `Logger.Writer`:
- No goroutines, no delays in logs
- You can implement your own writer in a configurable way (log level, custom fields, etc...)
- The above solution doesn't impose a limit on the logsize (as the Scanner used by `Logger.Writer` does)
- Writing a log that contains newlines appears as multiple logrus entries with the `Logger.Writer` solution because the scanner splits across newlines

**Comment by bklau** [comment]
@pasztorpisti I tried your solution. The only thing is that logrus will log all the messages from stdlog "log"  at INFO level. That can make it nosy if you have many warnings or debugs like so:

> origin x-app-id="ABCr" x-log-level="INFO" x-user-id="XYZ"] 2018-05-11T23:27:08Z /log_adapter.go:23 - RAFT Internal[WARN] raft: Heartbeat timeout from "" reached, starting election
> 
> [origin x-app-id="ABC" x-log-level="INFO" x-user-id="XYZ"] 2018-05-11T23:27:08Z /log_adapter.go:23 - RAFT Internal[INFO] raft: Node at 10.0.2.15:3131 [Candidate] entering Candidate state in term 3
> 
Note: The "RAFT Internal[INFO] raft" or "RAFT Internal[WARN] raft" is emitted by a std logger to io.Writer from logrus.

Q:  How do i  reconcile the log level of logrus to that of std "log"
