### ISSUE TITLE
Go to Definition in VS Code

### ISSUE THREAD

**Issue by joaodlf** [sirupsen/logrus#472]
This isn't so much of an issue, but it's strange because it's first package I encounter that has this behaviour.

I'm using VS Code as my editor and the excellent "Go" Extension for it, typically you can use the "Go to Definition" pretty much anywhere - Including all external packages installed via "go get". This isn't the case with logrus though, intellisense just doesn't seem to be available.

I found someone else with the same [issue](https://www.reddit.com/r/golang/comments/4tsbmk/using_logrus_with_vscode_no_peek_definition/).

Does anyone have any insight on this one?

**Comment by jtwatson** [comment]
I am running VSCode 1.9.0, Go plugin 0.6.53 on a macbook running Sierra and I do not experience any issue with intellisense or code navigation.

**Comment by sirupsen** [comment]
Hey, thanks for reporting. This problem is a little too narrow to be hunted down by the maintainers of this project, but I encourage you to dig in and propose changes that may be necessary upstream to fix this.

Thanks!

**Comment by tobyjwebb** [comment]
This may be because of Go modules. I found a workaround: (https://github.com/nsf/gocode/issues/444)

Go to go path:
cd ~/go/src

Do a go-get:
go get github.com/sirupsen/logrus

Once this is done, gocode should automagically pick up the Intellisense. (No need to restart the editor. - Well, not Atom, at least ;)
