### ISSUE TITLE
Strange characters printed when using TextFormatter

### ISSUE THREAD

**Issue by Acidic9** [sirupsen/logrus#486]
I just downloaded logrus and tried a few examples, and every single example prints some strange characters I believe where the colour should be changed.

I tried the following code
```go
package main

import (
	log "github.com/Sirupsen/logrus"
)

func main() {
	log.WithFields(log.Fields{
		"animal": "walrus",
	}).Info("A walrus appears")
}

```

And received the following output
```
?[34mINFO?[0m[0000] A walrus appears          ?[34manimal?[0m=walrus
```

I tried using both the git terminal as well as the windows CMD and both output the same result.

**Comment by leighmcculloch** [comment]
This happens because the windows cmd does not support the ANSI color escape codes. You have a couple options:

1. Use a terminal that supports ANSI colors. If you have Windows 10 you can enable the `Windows Subsystem for Linux` and then run `bash` in windows CMD and that will startup `Bash on Windows on Ubuntu`. Running your go app there should show colors.

2. The [README.md](https://github.com/sirupsen/logrus#formatters) mentions that you can use [github.com/mattn/go-colorable](https://github.com/mattn/go-colorable#usage) to support colors on logurs. Check it out.

3. Turn off colors:  
	```go
	package main

	import "github.com/sirupsen/logrus"

	func main() {
	    logrus.SetFormatter(&logrus.TextFormatter{DisableColors: true})
	    logrus.WithFields(logrus.Fields{
	        "animal": "walrus",
	    }).Info("A walrus appears")
	}
	```

**Comment by sirupsen** [comment]
Thanks @leighmcculloch 

This is also in the README

https://github.com/sirupsen/logrus#formatters
