### ISSUE TITLE
How can I make logrus print my stacktrace vertically? 

### ISSUE THREAD

**Issue by g-leon** [sirupsen/logrus#506]
In my project I use ```github.com/pkg/errors``` to build my errors. Sometimes I want to log the entire stacktrace with logrus but it will print the entire thing horizontally. How can I make logrus print my stacktrace vertically?

**Comment by mikeb333** [comment]
I think its because of the way logrus formats the values in the `TextFormatter`.  The formatter checks if there are special characters in value that require it to be quoted. Writing the string directly without calling `fmt.Sprintf("%q", stringVal)` yields a stacktrace that is vertical. Not sure how to leverage this directly though.

**Comment by LaysDragon** [comment]
You can do something like this via override TextFormater's Format method
```
type XerrorsTetFormatter struct {
	log.TextFormatter
}
func (f *XerrorsTetFormatter) Format(entry *log.Entry) ([]byte, error) {
	var entryError error
	for k, v := range entry.Data {
		if k == "error" {
			if unpackedErr,ok := v.(error) ;ok{
				entryError = unpackedErr
				delete(entry.Data,"error")
			}
		}
	}

	result, err := f.TextFormatter.Format(entry)
	b := bytes.NewBuffer(result)
	if entryError != nil{
		b.WriteString(fmt.Sprintf("error: %+v \n", entryError))
	}
	return b.Bytes(), err
}
```

```
log.WithError(err).Error("decode error")
```
