### ISSUE TITLE
Switch syscall to x/sys

### ISSUE THREAD

**Issue by clnperez** [sirupsen/logrus#515]
See https://github.com/opencontainers/runc/issues/1364 and  https://github.com/docker/docker/issues/31925

ppc64le is skipping some docker integration tests b/c this is broken. They weren't a big deal at the time but now that we know the root cause it would be great to address it. There may be other things wrong for other architectures as well, since syscall is being replaced by x/sys.

I'm working on this for runc, and then will try to get to docker/docker, so I figured I would open this as well since we know it's affecting ppc64le there as well.

**Comment by binarycrusader** [comment]
Since Go 1.4, any third-party Go code should start migrating to using the sys package instead of syscall, per the official Go documentation:

> NOTE: This package is locked down. Code outside the standard Go repository should be migrated to use the corresponding package in the golang.org/x/sys repository. That is also where updates required by new systems or versions should be applied. See https://golang.org/s/go1.4-syscall for more information. 

https://golang.org/pkg/syscall/

Notably, some Linux archs such as mips64, platforms such as Solaris, and others have large sets of functionality that are missing from the syscall package.  Because of the continued use of the syscall package, any new platforms, or those that were not completely supported at the time of Go 1.4 cannot build components such as this one.

/cc @epilatow

**Comment by clnperez** [comment]
@binarycrusader I'm not sure what you're getting at. Not trying to be snarky -- just genuinely confused. :)

I'm working on getting the legal approval (giant corporations have so many rules) to submit this fix, which I've tested on ppc64le. logrus works fine there.

**Comment by binarycrusader** [comment]
@clnperez not getting at anything; just supportive of the change since I've encountered the same issue on other platforms.  Thanks!
