### ISSUE TITLE
Add Trace level logging

### ISSUE THREAD

**Issue by xandrewrampulla** [sirupsen/logrus#629]
It would be very convenient if logrus had a TRACE level. There are times when I want to differentiate between log messages indicating where I am in the program vs. the on the wire messages (which can be very large).

**Comment by xandrewrampulla** [comment]
I added a PR https://github.com/sirupsen/logrus/pull/652 to help.

**Comment by xandrewrampulla** [comment]
I noticed there have been no commits since mid-August.  Is there a roadmap of releases and if so, what can I do to get this feature (with completed PR) into that release?

**Comment by chackett** [comment]
Well, I think that the author is seeking assistance with this project as he has many other commitments. I guess that there is no concrete roadmap as a result.

**Comment by pasztorpisti** [comment]
IMO having lots of log levels (eg.: a trace level) is a bad idea.

I prefer turning detailed trace/debug logs on/off with specific switches (bool variable or something similar) only in specific parts of the application instead of controlling this with one global switch (loglevel) that turns on trace everywhere and makes a larger piece of software completely unusable and/or undebuggable.

**Comment by chackett** [comment]
I'm inclined to disagree @pasztorpisti and in fact how do you implement trace in sub-components if it's not supported at a higher level? I mean to get the functionality of trace, it sounds like you are using Debug.

Component level log levels sounds like a cool _feature_ of your _system_ and potentially even in a logging framework but the levels still need to be supported at a higher level.

To your point on creating unusable, undebuggable software. No, trace would only get turned on for short periods of time. In any case, when in the depths of a production level issue, I would much rather have a bunch of verbose trace statements than much less of debug, which can only lead to taking longer to solve the problem.

**Comment by chackett** [comment]
Either way, Logrus is an open project for people to use with different use cases. To add trace would be trivial and in doing so would be enriching the library and cater for a wider audience and requirement set. If you don't agree with the log level, don't use it.

Perhaps I am missing the point..?

**Comment by pasztorpisti** [comment]
@chackett I'm pretty sure there are programmers who think trace is a good idea (and have some use cases for it) but my guess is that these programmers are a minority. The majority of projects never use or need trace even when it's available. For this reason I treat trace as a narrow purpose feature.

A good library (open source or not) has a simple, unambiguous, focused interface that solves the most important problems.

**Comment by chackett** [comment]
Trace doesn't create ambiguity .. it's another log level, which is explained in most good articles that explain logging. :/

**Comment by xandrewrampulla** [comment]
For what it is worth, the way I use trace (and IMO a great use case for it) is to create specialized loggers with a messaging library and log the wire format messages at trace level while logging other less interesting and verbose things (like the endpoints being hit) at debug level.  Being able to distinguish wireformat logs from less verbose, but still debug only messages is extremely valuable.

**Comment by pasztorpisti** [comment]
@chackett @xandrewrampulla 

For me trace is just debug log. Many devs have a similar opinion - I guess their number is higher than average in the go community that often follows KISS principles. [Here is an article](https://gualtierotesta.wordpress.com/2015/11/29/the-5-java-logging-rules/) explaining exactly what I think about trace:

> I personally discourage the use of the TRACE/FINEST level (and I’m not alone, see for example [here](https://www.slf4j.org/faq.html#trace)). I don’t see big difference between DEBUG and TRACE and it is usually difficult for the young team members to decide which one, DEBUG or TRACE, to use. Following the Kiss principle, I suggest to use ERROR, WARN, INFO and DEBUG levels only.

If we wanted to define a line between debug and trace based on verbosity: unfortunately it's subjective.

What happens if someone wants to differentiate 3 or 4 or more different debug log message categories, not only 2? Do we add another log level? (like log4j's fine, finest) In my opinion categorising debug log should be done in a different way, for example by adding a log field with different values: verbosity=1, verbosity=2, etc... and filter the log based on this field. I'd rather add an effective field-filtering mechanism than a new log level.

Filtering for multiple fields would make it possible to do interesting things like "subsystem=something level=debug verbosity=2"

**Comment by Random-Liu** [comment]
Here is our use case in Kubernetes https://github.com/sirupsen/logrus/issues/463#issuecomment-358133268

**Comment by dnephin** [comment]
As a compromise, how about adding an `entry.Log()` as an exported version of [entry.log()](https://github.com/sirupsen/logrus/blob/master/entry.go#L91) ?

That way users of the library can add extra log levels if they deem necessary, without adding anything significant to the API?

**Comment by dgsb** [comment]
solved by #844
