### ISSUE TITLE
systemd journal support

### ISSUE THREAD

**Issue by pquerna** [Sirupsen/logrus#66]
Systemd's journal support could be added by using the `go-systemd` lib:
https://github.com/coreos/go-systemd/blob/master/journal/send.go

It is kinda funny however to make it a "Hook" -- you kinda want it to be a log formatter, but the current interface for formatters assumes an io.Copy() interface, while for `journal.Send` you would want the 'formatter' to handle the 'write'.

A quick hack would be to allow Formatters to return `nil`, and in that case skip the io.Copy paths?

**Comment by mwhooker** [comment]
going to be implementing this internally. The use-case for us is journald will only read up to LINE_MAX characters per line, and our lines are a bit longer. LMK if anyone's interested and will see about open sourcing it.

**Comment by Sirupsen** [comment]
@mwhooker how are you going implement it?

**Comment by mwhooker** [comment]
@Sirupsen it's actually pretty simple

```go
func (hook *JournaldHook) Fire(entry *logrus.Entry) error {
	return journal.Send(entry.Message, severityMap[entry.Level], stringifyEntries(entry.Data))
}
```

where stringifyEntries has the signature `func stringifyEntries(data map[string]interface{}) map[string]string`

**Comment by mwhooker** [comment]
Here's the published library. https://github.com/wercker/journalhook

happy to take comments

**Comment by Sirupsen** [comment]
Thanks @mwhooker! 

Added to README 4d9b4f0

**Comment by davidnorthetal** [comment]
you can use stdout / stderr with systemd but systemd doesn't set the log-level accordingly
i.e. both stdout / stderr messages always have the same log-level for systemd

to circumvent that you have to do syslog or direct systemd journal logging

**Comment by gsauthof** [comment]
pauldotknopf [wrote](https://github.com/sirupsen/logrus/issues/66#issuecomment-440727245):
> It looks like this was removed from the readme.
> 
> Is there any particular reason? Is this still a valid approach?

Well, the readme now links to a [long hook list in the wiki](https://github.com/sirupsen/logrus/wiki/Hooks) which still includes the original systemd journald hook link.

I presume that at some point the hook list was moved to a separate page because it grew to long.

**Comment by potuz** [comment]
I couldn't find a proper place to ask for help so I figured I'll try in this issue since the hook page is archived. Using the journalhook with logs with fields like in 

```
log.WithFields(logrus.Fields{
                "att":      att,
                "dep":          dep,
                "lenatt": len(att),
        }).Info("Finished adding att")
```
Logging with the journalhook I'll see the message "Finshed adding att" but would not get the fields.

**Comment by gguridi** [comment]
@potuz the problem relies on the `journalhook` hook that you are using. If it's the same as the [wiki](https://github.com/sirupsen/logrus/wiki/Hooks) references then the problem is that the code is old and the Fire method is not using any formatter but directly sending the message only to the journal.

If you can't find another journalhook that uses the formatter, then copy that hook code into your project and make it use the formatter in your `Fire` method, like:

```golang
func (hook *JournalHook) Fire(entry *logrus.Entry) error {
        message, err := entry.String()
	if err == nil {
		return journal.Send(message, severityMap[entry.Level], stringifyEntries(entry.Data))
	}
	return err
}
```

Logrus is not responsible for hooks not using the formatters.
