### ISSUE TITLE
Separate log level constants 

### ISSUE THREAD

**Issue by olemis** [sirupsen/logrus#732]
Logging levels are consecutive integer numbers . By separating them it is possible to easily implement custom solutions for issues like #463 . For a previous reference, notice how default values for Python logging levels are not consecutive .

```sh
$ python3 -c "import logging as l ; print(l.CRITICAL, l.DEBUG, l.ERROR, l.FATAL, l.INFO, l.NOTSET, l.WARN, l.WARNING)"
50 10 40 50 20 0 30 30
```

p.s. this issue has been created as part of the work done in skycoin/skycoin#858 .

**Comment by gguridi** [comment]
I honestly think that the problem is Logrus exiting the program when a Fatal error happens. In fact, it's weird that if a Panic level happens (more severe) the program continues.

I think logrus should manage logs, and that's it. If the developer wants to stop the execution at that point then it's their responsibility to do so, but Logrus should never take that decision for you:

    logrus.Fatal("something happened")
    Exit(1)

**Comment by jacobwikibuy** [comment]
Then what is the difference between Fatal and Error?

**Comment by gguridi** [comment]
I think logrus implements it's own logging levels as many other systems (log4j, etc.). These levels go from Debug to Error. However, golang log interface implements its own two "special" log types [Fatal](https://golang.org/pkg/log/#Fatal) and [Panic](https://golang.org/pkg/log/#Panic).

To avoid problems integrating both of them, logrus implemented those two levels, but I don't think that my previous comment was 100% right. Panic is _not_ more severe than Fatal, they are just two extra levels with a Golang-defined meaning.
