### ISSUE TITLE
Deadlock in v1.0.5 due to fix of issue #683

### ISSUE THREAD

**Issue by gabiganam** [sirupsen/logrus#745]
In the following issue: [https://github.com/sirupsen/logrus/issues/683](url) a change was introduced that causes a deadlock in my code.
I have a hook that writes a log itself (within the Fire method of course), and it's hanging at entry.go, log method, on the mutex within fireHooks() method.

Am I doing something wrong?
The issue is reproducing 100% of the times in my code.

**Comment by gguridi** [comment]
I think the fix you are looking for is in the issue #703 and pull request #702.

**Comment by gabiganam** [comment]
Great, now all I have to do is wait for the merge and release of v1.0.6?
:)

**Comment by dgsb** [comment]
Indeed, if you use the same entry logger in a hook, you will have a deadlock as the logger mutex is taken again. This is needed and works as intended to protect entries against access races on the data field. Here you can have 3 options:
* if you are sure you do not need mutex on your logger because you are using it a single go routine, you can use the SetNoLock() call on the logger to not lock the mutex
* You can issue your other trace in a different go routine
* You can use a dedicated other Logger instance to issue traces within your hooks

**Comment by dgsb** [comment]
@gabiganam did you succeed to resolve your deadlock issue ?

**Comment by gabiganam** [comment]
Yes, I just logged in a new go routine; i.e. replaced this line:
logger.Errorf("reportPoints failed: %s", err)
with this line:
go logger.Errorf("reportPoints failed: %s", err) // New goroutine

Seems to be working fine now.
Thank you!
