### ISSUE TITLE
[Question] Logger with two backends and different levels

### ISSUE THREAD

**Issue by quentinlesceller** [sirupsen/logrus#790]
Hi everyone,

Basically I would like to do approximately the same as mentioned [here](https://stackoverflow.com/questions/38208608/go-logging-to-multiple-output). Copy pasting for readability.
Basically my main code would be:
```
log.Debug("Entering some func")
res := func()
log.Infof("Result was: %s", res)
```

I can see the console prints:

```
2015-03-26T01:27:38-04:00 [INFO]: Result was: Successful
```
And a file with:
```
2015-03-26T01:27:38-04:00 [DEBU]: Entering some func
2015-03-26T01:27:38-04:00 [INFO]: Result was: Successful
```

I managed to have the same content in both console and file (with a hook with https://github.com/rifflock/lfshook). However, I'd like to set a different log level for the two files in a conf file and be able to disable individually if needed. I'd like to avoid to create a logger object that I need to pass around (and instead the global logger) but not sure if that's possible.

**Comment by gguridi** [comment]
The lfshook hook is the way to go. If you don't want console output you can add `log.Out = ioutil.Discard` to your global logger.

Logging systems are by design not able to enable/disable logging handlers on runtime. That's why logrus doesn't allow to remove hooks. So once your application has started whatever has been configured will stay. For that, the lfshook I think it's enough to manage two file handlers with different log levels at same time.

**Comment by quentinlesceller** [comment]
Thanks for the answer @gguridi. I managed to do it several months ago with `lfshook` but it took me several hours. Closing then.
