### ISSUE TITLE
Is there a planned roadmap for performance to catch up with uber-go/zap?

### ISSUE THREAD

**Issue by vinerr** [sirupsen/logrus#803]
I am looking forward to it

**Comment by shahofblah** [comment]
Has [this](https://www.reddit.com/r/golang/comments/6irpt1/is_there_a_golang_logging_library_around_that/dj97phi/) been fixed?

I see 2 solutions here

1. Writer contention should be the only thing restricting concurrent access
2. Instead of a JSON marshal happening for every line of log, maybe a string formatting can be done instead? This is easy if the log object is only 1 level deep.

Another question

When calling log.SetOutput(), does logrus rely on the io.Writer to synchronise access or does it synchronise calls to the writer on its own?

In my service I use [lumberjack](https://github.com/natefinch/lumberjack) downstream from logrus to provide log rotation. Would this result in the same performance hit(lumberjack synchronises writes to the file. If logrus additionally synchronises calls to the writer, there's a needless performance hit.)

**Comment by dgsb** [comment]
No this has not been fixed because it has not been reported yet as an issue here.
We may create a dedicated performance project to check how to catch up with other logging library.
However, I suspect this is going to be hard without any massive interface change.
Regarding the JSON marshalling, there is another Formatter which just output text based on sprintf formatting.

**Comment by penhauer-xiao** [comment]
@dgsb Great ！

**Comment by nonpcnpc** [comment]
zerolog is now faster than zap. logrus is left behing, performance-wise :(
