### ISSUE TITLE
Branch management for 2.0

### ISSUE THREAD

**Issue by dgsb** [sirupsen/logrus#815]
We are regularly receiving incompatible changes with the 1.x versions.
In order to be able to incorporate those changes, we should dedicate a specific branch to allow further development without breaking existing contracts (e.g.,  2.0).

As it seems that mostly everyone uses master as is as 1.x compatible version, we are stuck with master being used for the v1. wdyt ?

**Comment by sirupsen** [comment]
Please keep master fully backwards compatible with no exceptions. It's far too relied upon that I want to compromise the trust of the community. I am conflicted on how to proceed for the future, safely.

**Comment by dgsb** [comment]
Indeed, that was what I was talking about. As the master branch is used in most project as the next version branch, we could also to avoid any fogginess freeze the master branch and use a dedicated v1 branch and create when wanted a v2 branch.

**Comment by sirupsen** [comment]
I think that's the way to go David.

By the way, thanks for all your stewardship here <img src="https://user-images.githubusercontent.com/97400/40184594-a4bc083a-59be-11e8-958d-20988af7f1ab.png" width="22" />

**Comment by theckman** [comment]
Agreed on wanting to keep things as stable as possible. We will want to make sure Go modules works correctly in the propsoed scenario. 

A question this brings up in my mind is at what point do people expect v2.0 to be the default and `master` being v1.0 starts to become a problem? I've not personally run in to other repos that do this, so logrus would be totally undoing assumptions I've been able to make about packages in the Go ecosystem. Are we okay with that? Is it healthy? I'm not sure I have an answer.

Do we have a bar for ever making master v2.0? If we never plan on doing that, does a 2.0 even make sense since they will most-likely end up on v1.0 and the newer features won't be exercised as much?

**Comment by dgodd** [comment]
I noticed this thread after open a PR to add go module support (https://github.com/sirupsen/logrus/pull/817). I believe that the current thinking for go modules and v2 versions is to create a directory `v2` inside the repository (rather than a branch). However given how much flux there is with go modules, I may be out of date with this statement.

**Comment by dgsb** [comment]
@dgodd from what I understand from this page https://github.com/golang/go/wiki/Modules we don't need to move code in a subdirectory when using go module. This is only need to import such path when NOT using go modules.

**Comment by aarongreenlee** [comment]
I suggest creating a new branch. Until Go Modules stabilize  I hesitate to adopt it within the `master` branch.

**Comment by dgsb** [comment]
@aarongreenlee module definition has already been added to the mastre branch. It should not have any  impact in the build process of package stored in $GOPATH/src, but can already be used by anyone else.
I think its important for a package as much used as logrus to quickly provide its modules definition in order to help other including package to also adopt/experiment with modules.

**Comment by dgsb** [comment]
@sirupsen, if you agree with the naming, I'm going to create `release-v1` and `release-v2` branches. I think only you has the rights to then perform the following options:
* define release-v1 as the default target branch for pull request
* potentially forbid merge request on master branch
* if you could also lock 1-0-stable as it seems to have never have been used
