### ISSUE TITLE
Catch Failed to fire hook

### ISSUE THREAD

**Issue by fabifrank** [sirupsen/logrus#876]
When there's a `Failed to fire hook` error, it seems there's no way to detect this error except from watching `stdout` of the process. How to know if firing a hook was successful or not (in call `entry.Debug` and similar)?

**Comment by fabifrank** [comment]
Does no one have an idea?

**Comment by richpoirier** [comment]
Hi @fabifrank. There doesn't seem to be an easy way no, but `Hook` is an interface so you could implement your own that does something with the error.

If you tell me your use case, I might be of better service.

**Comment by fabifrank** [comment]
Hi @richpoirier,

thanks for your answer! My program is adding an elasticsearch hook on startup. Now, if there's a network error later (for example elasticsearch server goes down and up again) the hook keeps failing. In this case, I wanted to catch the error and re-add the hook.

**Comment by richpoirier** [comment]
@fabifrank are you using https://github.com/sohlich/elogrus? I think you would want that project to implement retries rather than change logrus as it's not something that all hooks would need to do.

Here: https://github.com/sohlich/elogrus/blob/master/hook.go#L157, you could catch the `err` and retry and then only return an `err` after reaching a retry limit.

**Comment by fabifrank** [comment]
Thanks a lot @richpoirier that helped.
