### ISSUE TITLE
Maybe you should remove Entry

### ISSUE THREAD

**Issue by ZergsLaw** [sirupsen/logrus#987]
I apologize in advance for my English :)

The presence of two types creates a lot of inconvenience during wor, and it is better to work exclusively with the Logger type.
However, this leads to the fact that it is not possible to work normally with fields for more readable logging.

That`s why, I would like to suggest removing the type of Entry, and let the Logger to have a parent Logger as implemented in this project - https://github.com/powerman/structural

- examples of using are herehttps://github.com/powerman/structlog-usage-example

And yes, probably it is not correct to compare such big project to yours, BUT, I just would like to suggest a good solution of some "inconveniences" and If you'll send me a feedback I will send You PR

**Comment by pradykaushik** [comment]
The link that you have provided results in a 404.
Please provide the correct link.

**Comment by dgsb** [comment]
We can't  make breaking change in a v1

**Comment by ZergsLaw** [comment]
https://github.com/powerman/structlog

**Comment by ZergsLaw** [comment]
I can do it in version 2

**Comment by freeformz** [comment]
@ZergsLaw Sorry, but I'm having trouble understanding what problem you are experiencing with logrus. Both the Logger and Field types implement logrus.FieldLogger, so both can be passed around interchangeably. I often setup an instance of Logger in main to perform logging setup, then capture app contexts via WithField, which ends up with a Field, that is then passed to other types/packages to use for their logging. But those types / package can take either because they accept the interface (or sometimes a narrower one).

**Comment by belyshevdenis** [comment]
Please add example with logrus.FieldLogger to the README.

**Comment by freeformz** [comment]
@belyshevdenis It's not called out as such, but it's this pattern which I described: https://github.com/sirupsen/logrus/tree/fb62dbe2f2a2c88b150fa1668a773505a7920a3d#default-fields
