### ISSUE TITLE
no Go source files always appear after trying build the project

### ISSUE THREAD

**Issue by indoits** [sirupsen/logrus#992]
Hello, i have problem when trying build my project.

"cannot load github.com/sirupsen/logrus/hooks/syslog: no Go source files"

The error above always appear. I also do "go clean -modcache" but the error still appear. I searched for a resolution for similar cases but did not find and decided to find out here. This is my first post in the developer forum. I apologize if there is any wrong and lack. Thanks

**Comment by atc0005** [comment]
@indoits Did you ever find a solution for this problem? 

I experience this when attempting to build on Windows 10 with Go 1.13, but do not have the same issue when building within an Ubuntu 18.04 VM with the same version of Go. I've blown away my `$HOME/go` folder and tried again, but without success.

Note: I *have* enabled the use of Go modules. I'm not sure if that has anything to do with what you're experiencing, but I figure it's worth noting.

**Comment by atc0005** [comment]
I tried to download the package(s) from outside of my modules-enabled project and got back something different:

```ShellSession
C:\Users\atc0005>go get -v github.com/sirupsen/logrus
github.com/sirupsen/logrus (download)
```

```ShellSession
C:\Users\atc0005>go get -v github.com/sirupsen/logrus/hooks/syslog
can't load package: package github.com/sirupsen/logrus/hooks/syslog: build constraints exclude all Go files in C:\Users\atc0005\go\src\github.com\sirupsen\logrus\hooks\syslog
```

This bit stands out:

```
build constraints exclude all Go files in C:\Users\atc0005\go\src\github.com\sirupsen\logrus\hooks\syslog
```

Digging further, I found these references:

- https://github.com/go-delve/delve/issues/845
- https://stackoverflow.com/questions/24095004/cant-load-package-package-no-buildable-go-source-files
- https://golang.org/pkg/go/build/#hdr-Build_Constraints

When looking at the top line of both files, I find this:

```golang
// +build !windows,!nacl,!plan9
```

I'm too new to Go to say whether this is something that can/should be handled differently by the library, or if the build process is simply unhelpful in not pointing out that my platform is not supported for the build.

**Comment by atc0005** [comment]
Found a workaround, though I'm sure there is a better way: temporarily change `GOOS` from `windows` to `linux`.

From Git for Windows Bash shell:

```Bash
GOOS=linux go build
```

From Command Prompt: 

```CommandPrompt
set GOOS=linux
go build
```

I use Visual Studio Code, but I'm unaware of how to change `GOOS` just for the particular workspace where the build flag conflict is present. If it is supported somehow, that would likely be a better place to set the override.

**Comment by freeformz** [comment]
The `github.com/sirupsen/logrus/hooks/syslog` package will not build on Windows, Plan9, and nacl because the entirety of it is behind a set of [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) (via [build tags](
https://github.com/sirupsen/logrus/blob/master/hooks/syslog/syslog.go#L1)) that prevent it from being compiled on those platforms.

If you are writing some code that uses this package and expecting it to work on any of those platforms the code that uses the `github.com/sirupsen/logrus/hooks/syslog` package should also have the same build tags. These build tags were chosen because those are the same build tags that constrain the golang stdlib syslog package: https://golang.org/src/log/syslog/syslog.go

This is often worked around by providing a no-op implementation of the code that does not use the constrained package in seperate files (details in the golang build documentation linked above).

Super minimal example.

syslog_no-op.go
```go
// +build windows plan9 nacl

func (t *MyType) Syslog(...) { // no-op because syslog isn't generally a thing on windows
  // could also panic here or return an error
}
```

syslog.go
```go

// +build !windows, !plan9, !nacl

import github.com/sirupsen/logrus/hooks/syslog

func (t *MyType) Syslog(...) {
 ... // real implementation
}
```
