### ISSUE TITLE
Calling `logrus.Log` with `logrus.FatalLevel` should behave as `logrus.Fatal`

### ISSUE THREAD

**Issue by clafoutis42** [sirupsen/logrus#993]
I made an error wrapper for my project that embeds the logging level wanted for the error.  
Therefore I have a method that calls `logrus.Log(level, "error description")`, and I was surprised that if `level` is equal to `logrus.FatalLevel`, `logrus.Log` won't exit as `logrus.Fatal` would.  
Is this the wanted behavior ? If so, why ?

**Comment by pradykaushik** [comment]
Sorry for not getting to this sooner.
You are right that `logrus.Log(logrus.FatalLevel, args...)` does not exit.
AFAIK, this shouldn't be the intended behavior and [entry.log(...)](https://github.com/sirupsen/logrus/blob/master/entry.go#L206) is missing a check.
```go
if level == FatalLevel {
  entry.Logger.Exit(1)
}
```

@freeformz what are your thoughts on this?

**Comment by freeformz** [comment]
Either `logrus.Log(logrus.{Fatal,Panic}Level,...)` should log at that level and *not* panic / error or it log at that level and panic/error. ATM passing PanicLevel will cause a panic, but passing FataLevel will not: https://play.golang.org/p/nGDL1sBOkuD

Maybe @sirupsen or @dgsb can weigh in on which direction is the error, otherwise I'm going to have to review the git history to see if it indicates the intent.

FWIW: My inclination atm would be to make `Log(logrus.{Fatal,Panic}Level,...)`, *not* exit/panic. This would resolve #1028. My reasoning behind that is that logrus should allow *some* way to log at panic/fatal level w/o actually panicing/exiting, but that the .Panic/Fatal methods should absolutely continue to panic/exit. Research may change that opinion.

**Comment by jonmchan** [comment]
I would appreciate that @freeformz !

**Comment by dgsb** [comment]
@freeformz I'm not sure what was the initial intent, but we cannot change the behaviour. That would be a breaking change for v1 users.
We should indeed improve the documentation so that it's very clear on what is the expected behaviour.
